window.VOLUME = [
  { player:"Puka Nacua", pos:"WR", team:"LAR", market:"Receiving Yards", threshold:"20+", hits:20, games:20 },
  { player:"Chris Olave", pos:"WR", team:"NO", market:"Receiving Yards", threshold:"20+", hits:17, games:17 },
  { player:"Trey McBride", pos:"TE", team:"ARI", market:"Receiving Yards", threshold:"20+", hits:18, games:18 },
  { player:"Nico Collins", pos:"WR", team:"HOU", market:"Receiving Yards", threshold:"20+", hits:17, games:17 },
  { player:"Brock Bowers", pos:"TE", team:"LV", market:"Receiving Yards", threshold:"20+", hits:12, games:12 },
  { player:"Jaxon Smith-Njigba", pos:"WR", team:"SEA", market:"Receiving Yards", threshold:"20+", hits:19, games:20 },
  { player:"Christian McCaffrey", pos:"RB", team:"SF", market:"Receiving Yards", threshold:"20+", hits:19, games:20 },
  { player:"Tetairoa McMillan", pos:"WR", team:"CAR", market:"Receiving Yards", threshold:"20+", hits:18, games:19 },
  { player:"Amon-Ra St. Brown", pos:"WR", team:"DET", market:"Receiving Yards", threshold:"20+", hits:17, games:18 },
  { player:"George Pickens", pos:"WR", team:"DAL", market:"Receiving Yards", threshold:"20+", hits:17, games:18 },
  { player:"Davante Adams", pos:"WR", team:"LAR", market:"Receiving Yards", threshold:"20+", hits:17, games:18 },
  { player:"Jakobi Meyers", pos:"WR", team:"JAX", market:"Receiving Yards", threshold:"20+", hits:17, games:18 },
  { player:"Ja'Marr Chase", pos:"WR", team:"CIN", market:"Receiving Yards", threshold:"20+", hits:16, games:17 },
  { player:"DK Metcalf", pos:"WR", team:"PIT", market:"Receiving Yards", threshold:"20+", hits:16, games:17 },
  { player:"Harold Fannin Jr.", pos:"TE", team:"CLE", market:"Receiving Yards", threshold:"20+", hits:16, games:17 },
  { player:"Tee Higgins", pos:"WR", team:"CIN", market:"Receiving Yards", threshold:"20+", hits:15, games:16 },
  { player:"Dalton Kincaid", pos:"TE", team:"BUF", market:"Receiving Yards", threshold:"20+", hits:14, games:15 },
  { player:"CeeDee Lamb", pos:"WR", team:"DAL", market:"Receiving Yards", threshold:"20+", hits:13, games:14 },
  { player:"Drake London", pos:"WR", team:"ATL", market:"Receiving Yards", threshold:"20+", hits:12, games:13 },
  { player:"Christian Watson", pos:"WR", team:"GB", market:"Receiving Yards", threshold:"20+", hits:11, games:12 },
  { player:"Terry McLaurin", pos:"WR", team:"WAS", market:"Receiving Yards", threshold:"20+", hits:10, games:11 },
  { player:"Sam LaPorta", pos:"TE", team:"DET", market:"Receiving Yards", threshold:"20+", hits:9, games:10 },
  { player:"Cooper Kupp", pos:"WR", team:"SEA", market:"Receiving Yards", threshold:"20+", hits:18, games:20 },
  { player:"DeVonta Smith", pos:"WR", team:"PHI", market:"Receiving Yards", threshold:"20+", hits:17, games:19 },
  { player:"Keenan Allen", pos:"WR", team:"IND", market:"Receiving Yards", threshold:"20+", hits:17, games:19 },

  { player:"Puka Nacua", pos:"WR", team:"LAR", market:"Receptions", threshold:"2+", hits:20, games:20 },
  { player:"Trey McBride", pos:"TE", team:"ARI", market:"Receptions", threshold:"2+", hits:18, games:18 },
  { player:"Ja'Marr Chase", pos:"WR", team:"CIN", market:"Receptions", threshold:"2+", hits:17, games:17 },
  { player:"Jaxon Smith-Njigba", pos:"WR", team:"SEA", market:"Receptions", threshold:"2+", hits:20, games:20 },
  { player:"Chris Olave", pos:"WR", team:"NO", market:"Receptions", threshold:"2+", hits:17, games:17 },
  { player:"Justin Jefferson", pos:"WR", team:"MIN", market:"Receptions", threshold:"2+", hits:18, games:18 },
  { player:"Zay Flowers", pos:"WR", team:"BAL", market:"Receptions", threshold:"2+", hits:18, games:18 },
  { player:"Bijan Robinson", pos:"RB", team:"ATL", market:"Receptions", threshold:"2+", hits:18, games:18 },
  { player:"Nico Collins", pos:"WR", team:"HOU", market:"Receptions", threshold:"2+", hits:17, games:17 },
  { player:"Stefon Diggs", pos:"WR", team:"WAS", market:"Receptions", threshold:"2+", hits:20, games:20 },
  { player:"Deebo Samuel", pos:"WR", team:"WAS", market:"Receptions", threshold:"2+", hits:17, games:17 },
  { player:"Sam LaPorta", pos:"TE", team:"DET", market:"Receptions", threshold:"2+", hits:10, games:10 },
  { player:"Juwan Johnson", pos:"TE", team:"NO", market:"Receptions", threshold:"2+", hits:18, games:18 },
  { player:"Tyler Warren", pos:"TE", team:"IND", market:"Receptions", threshold:"2+", hits:18, games:18 },
  { player:"Harold Fannin Jr.", pos:"TE", team:"CLE", market:"Receptions", threshold:"2+", hits:17, games:17 },
  { player:"Chase Brown", pos:"RB", team:"CIN", market:"Receptions", threshold:"2+", hits:18, games:18 },
  { player:"DK Metcalf", pos:"WR", team:"PIT", market:"Receptions", threshold:"2+", hits:17, games:17 },
  { player:"Christian Watson", pos:"WR", team:"GB", market:"Receptions", threshold:"2+", hits:12, games:12 },
  { player:"Terry McLaurin", pos:"WR", team:"WAS", market:"Receptions", threshold:"2+", hits:11, games:11 },
  { player:"Jonathan Taylor", pos:"RB", team:"IND", market:"Receptions", threshold:"2+", hits:17, games:17 },
  { player:"Christian McCaffrey", pos:"RB", team:"SF", market:"Receptions", threshold:"2+", hits:19, games:20 },
  { player:"Dalton Schultz", pos:"TE", team:"HOU", market:"Receptions", threshold:"2+", hits:19, games:20 },
  { player:"Keenan Allen", pos:"WR", team:"IND", market:"Receptions", threshold:"2+", hits:18, games:19 },
  { player:"DeVonta Smith", pos:"WR", team:"PHI", market:"Receptions", threshold:"2+", hits:18, games:19 },
  { player:"Amon-Ra St. Brown", pos:"WR", team:"DET", market:"Receptions", threshold:"2+", hits:17, games:18 },

  { player:"Derrick Henry", pos:"RB", team:"BAL", market:"Rushing Yards", threshold:"20+", hits:18, games:18 },
  { player:"Jonathan Taylor", pos:"RB", team:"IND", market:"Rushing Yards", threshold:"20+", hits:18, games:18 },
  { player:"Bijan Robinson", pos:"RB", team:"ATL", market:"Rushing Yards", threshold:"20+", hits:18, games:18 },
  { player:"Saquon Barkley", pos:"RB", team:"PHI", market:"Rushing Yards", threshold:"20+", hits:18, games:18 },
  { player:"J.K. Dobbins", pos:"RB", team:"DEN", market:"Rushing Yards", threshold:"20+", hits:11, games:11 },
  { player:"Javonte Williams", pos:"RB", team:"DAL", market:"Rushing Yards", threshold:"20+", hits:17, games:17 },
  { player:"Kyren Williams", pos:"RB", team:"LAR", market:"Rushing Yards", threshold:"20+", hits:20, games:20 },
  { player:"Breece Hall", pos:"RB", team:"NYJ", market:"Rushing Yards", threshold:"20+", hits:17, games:17 },
  { player:"Christian McCaffrey", pos:"RB", team:"SF", market:"Rushing Yards", threshold:"20+", hits:20, games:20 },
  { player:"Travis Etienne Jr.", pos:"RB", team:"NO", market:"Rushing Yards", threshold:"20+", hits:19, games:19 },
  { player:"James Cook III", pos:"RB", team:"BUF", market:"Rushing Yards", threshold:"20+", hits:19, games:20 },
  { player:"Kenneth Walker III", pos:"RB", team:"KC", market:"Rushing Yards", threshold:"20+", hits:19, games:20 },
  { player:"D'Andre Swift", pos:"RB", team:"CHI", market:"Rushing Yards", threshold:"20+", hits:18, games:19 },
  { player:"Tony Pollard", pos:"RB", team:"TEN", market:"Rushing Yards", threshold:"20+", hits:17, games:18 },
  { player:"Ashton Jeanty", pos:"RB", team:"LV", market:"Rushing Yards", threshold:"20+", hits:17, games:18 },
  { player:"Chase Brown", pos:"RB", team:"CIN", market:"Rushing Yards", threshold:"20+", hits:17, games:18 },
  { player:"Jaylen Warren", pos:"RB", team:"PIT", market:"Rushing Yards", threshold:"20+", hits:17, games:18 },
  { player:"Jacory Croskey-Merritt", pos:"RB", team:"WAS", market:"Rushing Yards", threshold:"20+", hits:17, games:18 },
  { player:"De'Von Achane", pos:"RB", team:"MIA", market:"Rushing Yards", threshold:"20+", hits:16, games:17 },
  { player:"Quinshon Judkins", pos:"RB", team:"CLE", market:"Rushing Yards", threshold:"20+", hits:14, games:15 },
  { player:"Bucky Irving", pos:"RB", team:"TB", market:"Rushing Yards", threshold:"20+", hits:10, games:11 },
  { player:"Omarion Hampton", pos:"RB", team:"LAC", market:"Rushing Yards", threshold:"20+", hits:10, games:11 },
  { player:"Jahmyr Gibbs", pos:"RB", team:"DET", market:"Rushing Yards", threshold:"20+", hits:16, games:18 },
  { player:"Jordan Mason", pos:"RB", team:"MIN", market:"Rushing Yards", threshold:"20+", hits:15, games:17 },
  { player:"Aaron Jones Sr.", pos:"RB", team:"MIN", market:"Rushing Yards", threshold:"20+", hits:11, games:13 },

  { player:"Jared Goff", pos:"QB", team:"DET", market:"Passing Yards", threshold:"150+", hits:18, games:18 },
  { player:"Patrick Mahomes", pos:"QB", team:"KC", market:"Passing Yards", threshold:"150+", hits:15, games:15 },
  { player:"Caleb Williams", pos:"QB", team:"CHI", market:"Passing Yards", threshold:"150+", hits:20, games:20 },
  { player:"Trevor Lawrence", pos:"QB", team:"JAX", market:"Passing Yards", threshold:"150+", hits:19, games:19 },
  { player:"Matthew Stafford", pos:"QB", team:"LAR", market:"Passing Yards", threshold:"150+", hits:19, games:20 },
  { player:"Drake Maye", pos:"QB", team:"NE", market:"Passing Yards", threshold:"150+", hits:19, games:20 },
  { player:"Dak Prescott", pos:"QB", team:"DAL", market:"Passing Yards", threshold:"150+", hits:17, games:18 },
  { player:"C.J. Stroud", pos:"QB", team:"HOU", market:"Passing Yards", threshold:"150+", hits:16, games:17 },
  { player:"Jacoby Brissett", pos:"QB", team:"ARI", market:"Passing Yards", threshold:"150+", hits:13, games:14 },
  { player:"Daniel Jones", pos:"QB", team:"IND", market:"Passing Yards", threshold:"150+", hits:13, games:14 },
  { player:"Bo Nix", pos:"QB", team:"DEN", market:"Passing Yards", threshold:"150+", hits:17, games:19 },
  { player:"Justin Herbert", pos:"QB", team:"LAC", market:"Passing Yards", threshold:"150+", hits:16, games:18 },
  { player:"Jordan Love", pos:"QB", team:"GB", market:"Passing Yards", threshold:"150+", hits:15, games:17 },
  { player:"Lamar Jackson", pos:"QB", team:"BAL", market:"Passing Yards", threshold:"150+", hits:12, games:14 },
  { player:"Josh Allen", pos:"QB", team:"BUF", market:"Passing Yards", threshold:"150+", hits:16, games:19 },
  { player:"Brock Purdy", pos:"QB", team:"SF", market:"Passing Yards", threshold:"150+", hits:10, games:12 },
  { player:"Baker Mayfield", pos:"QB", team:"TB", market:"Passing Yards", threshold:"150+", hits:15, games:18 },
  { player:"Aaron Rodgers", pos:"QB", team:"PIT", market:"Passing Yards", threshold:"150+", hits:14, games:18 },
  { player:"Jalen Hurts", pos:"QB", team:"PHI", market:"Passing Yards", threshold:"150+", hits:14, games:18 },
  { player:"Jaxson Dart", pos:"QB", team:"NYG", market:"Passing Yards", threshold:"150+", hits:10, games:13 },
  { player:"Tyler Shough", pos:"QB", team:"NO", market:"Passing Yards", threshold:"150+", hits:9, games:12 },
  { player:"Joe Flacco", pos:"QB", team:"CIN", market:"Passing Yards", threshold:"150+", hits:9, games:12 },
  { player:"Geno Smith", pos:"QB", team:"NYJ", market:"Passing Yards", threshold:"150+", hits:12, games:16 },
  { player:"Kirk Cousins", pos:"QB", team:"LV", market:"Passing Yards", threshold:"150+", hits:8, games:11 },
  { player:"Bryce Young", pos:"QB", team:"CAR", market:"Passing Yards", threshold:"150+", hits:13, games:18 }
];

window.PRESETS = [
  { label:"WR 20+ yds", pos:"WR", market:"Receiving Yards", minHits:16 },
  { label:"WR 2+ rec", pos:"WR", market:"Receptions", minHits:16 },
  { label:"TE 20+ yds", pos:"TE", market:"Receiving Yards", minHits:12 },
  { label:"TE 2+ rec", pos:"TE", market:"Receptions", minHits:12 },
  { label:"RB 20+ rush", pos:"RB", market:"Rushing Yards", minHits:16 },
  { label:"QB 150+ pass", pos:"QB", market:"Passing Yards", minHits:16 }
];
